# -*- coding: utf-8 -*-

classical_info_list = ['START_SENDING_PHOTONS','STARTED','PHOTON_TRANSMISSION_OVER','PHOTON_RECEIVAL_COMPLETE','KEY_SIFTING_OVER','PRELIMINARY_ERROR_CHECK_OVER','INFORMATION_RECONCILIATION_STARTED','INFORMATION_RECONCILIATION_OVER','PRIVACY_AMPLIFICATION_STARTED','PRIVACY_AMPLIFICATION_OVER','ABORT_QKD']